Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "spec/**/*.rb"
Layout/LineLength:
  Enabled: true
  Exclude:
    - 'lib/parser/presenter/*.rb'

# Prefer class documentation above module.
Style/Documentation:
  Enabled: false
