jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.1.1
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec

  rubocop:
    docker:
      - image: cimg/ruby:3.1.1
    steps:
      - checkout
      - run: bundle install
      - run: rubocop .

workflows:
  version: 2
  build_and_test:
    jobs:
      - rubocop
      - rspec
