version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    executor: ruby/default
    docker:
      - image: cimg/ruby:3.1.1
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec
